image:
  name: 377877851685.dkr.ecr.eu-west-1.amazonaws.com/origin-public-ip
  tag: latest
  pullPolicy: Always


app:
  containerPort: 3000

  resources:
  requests:
    cpu: 125m
    memory: 256Mi

  defaultProbe:
    httpGet:
      path: "/"
      port: 3000
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 1
    successThreshold: 1
