image:
<<<<<<< HEAD:helm-chart/origin-public-ip/values.yaml
  name: 377877851685.dkr.ecr.eu-west-1.amazonaws.com/origin-public-ip
=======
  name: europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/origin-public-ip:staging
>>>>>>> 7b7d4c7 (set up github actions):helm-chart/templates/values.yaml
  tag: staging
  pullPolicy: Always


app:
  containerPort: 3000

  resources:
  requests:
    cpu: 125m
    memory: 256Mi

  defaultProbe:
    httpGet:
      path: "/health"
      port: 3000
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 1
    successThreshold: 1
