image:
  name: europe-west9-docker.pkg.dev/$GOOGLE_PROJECT/origin-public-ip:staging
  tag: staging
  pullPolicy: Always


app:
  containerPort: 3000

  resources:
  requests:
    cpu: 125m
    memory: 256Mi

  defaultProbe:
    httpGet:
      path: "/"
      port: 3000
    initialDelaySeconds: 20
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 1
    successThreshold: 1
