apiVersion: v1
kind: Service
metadata:
  name: {{ include "origin-public-ip.app.name" . }}
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: {{ include "origin-public-ip.app.name" . }}
  ports:
  - port: 80
    targetPort: 3000
