name: Deploy Origin-public-ip

on:
  push:
    branches:
    - 'staging'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-2
  GKE_ZONE: europe-west9
  IMAGE: origin-public-ip
  IMAGE_TAG: latest 
  GAR_ZONE: europe-west9
  GAR_REPO: sample-app

jobs:
  setup-and-build:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - name: Docker configuration
      run: |-
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://$GAR_ZONE-docker.pkg.dev

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE:$IMAGE_TAG" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$GAR_ZONE-docker.pkg.dev/$PROJECT_ID/$GAR_REPO/$IMAGE:$IMAGE_TAG"

    # - name: deploy to gke
    #   env:
    #     GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
    #   run: |
    #     gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_ZONE
    #     cd helm-chart/templates
    #     rm -fr charts/*
    #     rm -fr out/
    #     helm lint
    #     helm package -d charts .
    #     helm upgrade $IMAGE $(ls charts/$IMAGE-*.tgz) \
    #           --atomic --install \
    #           --namespace production

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: $GKE_CLUSTER
        location: $GKE_ZONE
        project_id: $PROJECT_ID

    - name: Deploy on the GKE
      run: |-
        cd helm-chart/templates
        rm -fr charts/*
        rm -fr out/
        helm lint
        helm package -d charts .
        helm upgrade $IMAGE $(ls charts/$IMAGE-*.tgz) \
              --atomic --install \
              --namespace production
